# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import aegis.compliance as module_0


def test_case_0():
    i_c_n_i_r_p_limits_0 = module_0.icnirp_limits()
    assert (
        f"{type(i_c_n_i_r_p_limits_0).__module__}.{type(i_c_n_i_r_p_limits_0).__qualname__}"
        == "aegis.compliance.ICNIRPLimits"
    )
    assert i_c_n_i_r_p_limits_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert i_c_n_i_r_p_limits_0.freq_hz == pytest.approx(
        28000000000.0, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sab_4cm2 == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sab_1cm2 is None
    assert i_c_n_i_r_p_limits_0.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sinc_local == pytest.approx(
        30.494092823320592, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sinc_whole_body == pytest.approx(
        10.0, abs=0.01, rel=0.01
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    float_0 = 299999999991.25116
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sab_1cm2=float_0, sar_wb=float_0, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999991.25116, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert (
        f"{type(compliance_result_0.sab_1cm2).__module__}.{type(compliance_result_0.sab_1cm2).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    none_type_0 = None
    module_0.is_compliant_sab(none_type_0)


def test_case_2():
    float_0 = 299999999987.1448
    dict_0 = module_0.link_budget_compliance(
        tx_power_w=float_0, distance_m=float_0, freq_hz=float_0
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    bool_0 = module_0.is_compliant_sar(float_0)
    assert bool_0 is False


def test_case_3():
    bool_0 = True
    with pytest.raises(ValueError):
        module_0.link_budget_compliance(
            tx_power_w=bool_0, distance_m=bool_0, freq_hz=bool_0, T0=bool_0
        )


def test_case_4():
    i_c_n_i_r_p_limits_0 = module_0.icnirp_limits()
    assert (
        f"{type(i_c_n_i_r_p_limits_0).__module__}.{type(i_c_n_i_r_p_limits_0).__qualname__}"
        == "aegis.compliance.ICNIRPLimits"
    )
    assert i_c_n_i_r_p_limits_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert i_c_n_i_r_p_limits_0.freq_hz == pytest.approx(
        28000000000.0, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sab_4cm2 == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sab_1cm2 is None
    assert i_c_n_i_r_p_limits_0.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sinc_local == pytest.approx(
        30.494092823320592, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sinc_whole_body == pytest.approx(
        10.0, abs=0.01, rel=0.01
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    float_0 = -4244.643387
    with pytest.raises(ValueError):
        module_0.margin_db(float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = -890.41
    module_0.link_budget_compliance(
        tx_power_w=float_0, distance_m=float_0, freq_hz=float_0
    )


def test_case_6():
    bool_0 = True
    float_0 = module_0.margin_db(bool_0, bool_0)
    assert float_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    i_c_n_i_r_p_limits_0 = module_0.icnirp_limits()
    assert (
        f"{type(i_c_n_i_r_p_limits_0).__module__}.{type(i_c_n_i_r_p_limits_0).__qualname__}"
        == "aegis.compliance.ICNIRPLimits"
    )
    assert i_c_n_i_r_p_limits_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert i_c_n_i_r_p_limits_0.freq_hz == pytest.approx(
        28000000000.0, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sab_4cm2 == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sab_1cm2 is None
    assert i_c_n_i_r_p_limits_0.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sinc_local == pytest.approx(
        30.494092823320592, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sinc_whole_body == pytest.approx(
        10.0, abs=0.01, rel=0.01
    )


def test_case_7():
    float_0 = 299999999998.78925
    dict_0 = module_0.link_budget_compliance(
        tx_power_w=float_0, distance_m=float_0, freq_hz=float_0
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )


def test_case_8():
    float_0 = 2438.91571
    bool_0 = False
    float_1 = module_0.margin_db(float_0, bool_0)
    assert float_1 == pytest.approx(-1e309, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )


def test_case_9():
    none_type_0 = None
    bool_0 = False
    with pytest.raises(ValueError):
        module_0.max_compliant_power(none_type_0, bool_0)


def test_case_10():
    float_0 = 300000000021.6749
    bool_0 = True
    with pytest.raises(ValueError):
        module_0.link_budget_compliance(
            tx_power_w=bool_0, distance_m=float_0, freq_hz=float_0
        )


def test_case_11():
    exposure_scenario_0 = module_0.ExposureScenario.OCCUPATIONAL
    i_c_n_i_r_p_limits_0 = module_0.icnirp_limits(exposure_scenario_0)
    assert (
        f"{type(i_c_n_i_r_p_limits_0).__module__}.{type(i_c_n_i_r_p_limits_0).__qualname__}"
        == "aegis.compliance.ICNIRPLimits"
    )
    assert i_c_n_i_r_p_limits_0.scenario == module_0.ExposureScenario.OCCUPATIONAL
    assert i_c_n_i_r_p_limits_0.freq_hz == pytest.approx(
        28000000000.0, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sab_4cm2 == pytest.approx(100.0, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sab_1cm2 is None
    assert i_c_n_i_r_p_limits_0.sar_wb == pytest.approx(0.4, abs=0.01, rel=0.01)
    assert i_c_n_i_r_p_limits_0.sinc_local == pytest.approx(
        152.47046411660295, abs=0.01, rel=0.01
    )
    assert i_c_n_i_r_p_limits_0.sinc_whole_body == pytest.approx(
        50.0, abs=0.01, rel=0.01
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )


def test_case_12():
    float_0 = 299999999990.5307
    int_0 = -669
    with pytest.raises(ValueError):
        module_0.link_budget_compliance(
            tx_power_w=float_0, distance_m=int_0, freq_hz=float_0, scenario=float_0
        )


def test_case_13():
    float_0 = 300000000000.0
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=float_0, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        300000000000.0, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_14():
    float_0 = 299999999992.85144
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sab_4cm2=float_0, sar_wb=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999992.85144, abs=0.01, rel=0.01
    )
    assert (
        f"{type(compliance_result_0.sab_4cm2).__module__}.{type(compliance_result_0.sab_4cm2).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_15():
    float_0 = 299999999991.5
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, scenario=float_0, sab_4cm2=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == pytest.approx(
        299999999991.5, abs=0.01, rel=0.01
    )
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999991.5, abs=0.01, rel=0.01
    )
    assert (
        f"{type(compliance_result_0.sab_4cm2).__module__}.{type(compliance_result_0.sab_4cm2).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sab_1cm2 is None
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_16():
    float_0 = 299999999991.45593
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=float_0, sinc_local=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999991.45593, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert (
        f"{type(compliance_result_0.sinc_local).__module__}.{type(compliance_result_0.sinc_local).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_17():
    float_0 = 299999999999.97595
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sab_1cm2=float_0, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999999.97595, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert (
        f"{type(compliance_result_0.sab_1cm2).__module__}.{type(compliance_result_0.sab_1cm2).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_18():
    float_0 = 30000000000.0
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sab_1cm2=float_0, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        30000000000.0, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


def test_case_19():
    float_0 = 299999999998.78925
    dict_0 = module_0.link_budget_compliance(
        tx_power_w=float_0,
        distance_m=float_0,
        freq_hz=float_0,
        T0=float_0,
        scenario=float_0,
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )


@pytest.mark.xfail(strict=True)
def test_case_20():
    float_0 = 6000000000.0
    module_0.link_budget_compliance(
        tx_power_w=float_0, distance_m=float_0, freq_hz=float_0
    )


def test_case_21():
    float_0 = 299999999999.7949
    compliance_result_0 = module_0.evaluate_compliance(freq_hz=float_0, sar_wb=float_0)
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999999.7949, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0, float_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\nTx power: 299999999999.8 dBm\n\n  SAR_wb: 3e+11 / 0.08 W/kg [FAIL] (margin -125.7 dB)\n\nOverall: FAIL (tightest margin: -125.7 dB)"
    )


def test_case_22():
    float_0 = 299999999999.7949
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sinc_local=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999999.7949, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert compliance_result_0.sar_wb is None
    assert (
        f"{type(compliance_result_0.sinc_local).__module__}.{type(compliance_result_0.sinc_local).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\n\n  S_inc (local): 3e+11 / 20.0407 W/m^2 [FAIL] (margin -101.8 dB)\n\nOverall: FAIL (tightest margin: -101.8 dB)"
    )


def test_case_23():
    float_0 = 299999999999.8
    none_type_0 = None
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=none_type_0, sinc_whole_body=none_type_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999999.8, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\n\n\nOverall: N/A (tightest margin: +inf dB)"
    )


def test_case_24():
    float_0 = 299999999992.2079
    float_1 = 0.0
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=float_1, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999992.2079, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\n\n  SAR_wb: 0 / 0.08 W/kg [PASS] (margin +inf dB)\n  S_inc (whole-body): 3e+11 / 10 W/m^2 [FAIL] (margin -104.8 dB)\n\nOverall: FAIL (tightest margin: -104.8 dB)"
    )


def test_case_25():
    float_0 = 299999999992.2079
    float_1 = 1e-20
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=float_1, sinc_whole_body=float_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999992.2079, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert (
        f"{type(compliance_result_0.sinc_whole_body).__module__}.{type(compliance_result_0.sinc_whole_body).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\n\n  SAR_wb: 1e-20 / 0.08 W/kg [PASS] (margin +189.0 dB)\n  S_inc (whole-body): 3e+11 / 10 W/m^2 [FAIL] (margin -104.8 dB)\n\nOverall: FAIL (tightest margin: -104.8 dB)"
    )


def test_case_26():
    float_0 = 299999999968.3318
    int_0 = -116
    compliance_result_0 = module_0.evaluate_compliance(freq_hz=float_0, sab_1cm2=int_0)
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999968.3318, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert (
        f"{type(compliance_result_0.sab_1cm2).__module__}.{type(compliance_result_0.sab_1cm2).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    str_0 = module_0.summary_text(compliance_result_0)
    assert (
        str_0
        == "ICNIRP 2020 compliance (general_public)\nFrequency: 300.000 GHz\n\n  S_ab (1 cm^2): -116 / 40 W/m^2 [PASS] (margin +inf dB)\n\nOverall: PASS (tightest margin: +inf dB)"
    )


def test_case_27():
    float_0 = 299999999990.7207
    float_1 = 3500000000.0
    float_2 = 299999999967.00507
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_1,
        sab_4cm2=float_0,
        sab_1cm2=float_0,
        sar_wb=float_2,
        sinc_whole_body=float_2,
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        3500000000.0, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert (
        f"{type(compliance_result_0.sar_wb).__module__}.{type(compliance_result_0.sar_wb).__qualname__}"
        == "aegis.compliance.ComplianceCheck"
    )
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )


@pytest.mark.xfail(strict=True)
def test_case_28():
    float_0 = 299999999958.0
    float_1 = 299999999942.2913
    float_2 = -3076.8
    none_type_0 = None
    module_0.link_budget_compliance(
        tx_power_w=float_1,
        antenna_gain_dbi=float_2,
        distance_m=float_0,
        freq_hz=float_0,
        T0=none_type_0,
    )


@pytest.mark.xfail(strict=True)
def test_case_29():
    int_0 = 1150
    float_0 = 299999999954.4232
    float_1 = -3077.0
    none_type_0 = None
    module_0.link_budget_compliance(
        tx_power_w=int_0,
        antenna_gain_dbi=float_1,
        distance_m=float_0,
        freq_hz=float_0,
        T0=none_type_0,
    )


def test_case_30():
    float_0 = 299999999965.8289
    none_type_0 = None
    compliance_result_0 = module_0.evaluate_compliance(
        freq_hz=float_0, sar_wb=none_type_0
    )
    assert (
        f"{type(compliance_result_0).__module__}.{type(compliance_result_0).__qualname__}"
        == "aegis.compliance.ComplianceResult"
    )
    assert compliance_result_0.scenario == module_0.ExposureScenario.GENERAL_PUBLIC
    assert compliance_result_0.freq_hz == pytest.approx(
        299999999965.8289, abs=0.01, rel=0.01
    )
    assert compliance_result_0.sab_4cm2 is None
    assert compliance_result_0.sab_1cm2 is None
    assert compliance_result_0.sar_wb is None
    assert compliance_result_0.sinc_local is None
    assert compliance_result_0.sinc_whole_body is None
    assert module_0.ICNIRP_2020.sab_peak == pytest.approx(20.0, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.sar_wb == pytest.approx(0.08, abs=0.01, rel=0.01)
    assert module_0.ICNIRP_2020.averaging_area_cm2 == pytest.approx(
        4.0, abs=0.01, rel=0.01
    )
    assert (
        f"{type(module_0.ComplianceResult.all_checks).__module__}.{type(module_0.ComplianceResult.all_checks).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.overall_pass).__module__}.{type(module_0.ComplianceResult.overall_pass).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.ComplianceResult.margin_db).__module__}.{type(module_0.ComplianceResult.margin_db).__qualname__}"
        == "builtins.property"
    )
    float_1 = module_0.max_compliant_power(compliance_result_0, float_0)
    assert float_1 == pytest.approx(1e309, abs=0.01, rel=0.01)
