"""Assemble the report's generated artifacts from a study batch.

Reads ``results/cities/cities_summary.json`` (written by
``aegis.study.run_cities``), copies the overlay CDF figure into ``figures/``,
and writes ``figures/cities_table.tex`` (per-city median and p95). Run after the
batch, then build with pdflatex. See README.md.

Usage:
    python papers/city-exposure-study/make_report.py [--results results/cities]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).parent
FIGS = HERE / "figures"

# Headline-metric axis labels.
_XLABEL = {
    "p_abs_w": r"Whole-body absorbed power $\mathbf{x}^H Q\,\mathbf{x}$ [W]",
    "icnirp_fraction": "ICNIRP fraction",
}


def _fmt(x):
    return "--" if x is None else f"\\num{{{x:.3e}}}"


def _render_overlay(cities, stem):
    """Regenerate the per-city CDF overlay from saved (cdf_x, cdf_f). Decoupled
    from the batch so the figure can be restyled without re-running the study."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    try:
        import scienceplots  # noqa: F401

        plt.style.use(["science", "ieee"])
    except Exception:
        pass

    headline = cities[0].get("headline", "exposure") if cities else "exposure"
    fig, ax = plt.subplots(figsize=(3.5, 2.7))
    any_positive = False
    for c in sorted(cities, key=lambda r: r.get("median") or 0.0):
        x = np.asarray(c.get("cdf_x", []), dtype=float)
        f = np.asarray(c.get("cdf_f", []), dtype=float)
        if x.size:
            ax.step(x, f, where="post", label=str(c.get("name", "?")).replace("_", " ").title(), lw=0.9)
            any_positive = any_positive or bool(np.any(x > 0))
    # Absorbed power and ICNIRP fraction both span orders of magnitude -> log x.
    if any_positive:
        ax.set_xscale("log")
    ax.set_xlabel(_XLABEL.get(headline, headline))
    ax.set_ylabel("Population CDF")
    ax.set_ylim(0, 1)
    ax.legend(fontsize=5, ncol=2, frameon=False, loc="lower right")
    fig.tight_layout()
    fig.savefig(f"{stem}.pdf")
    fig.savefig(f"{stem}.png", dpi=220)
    plt.close(fig)
    print(f"rendered {stem}.pdf and .png from {len(cities)} cities")


def _render_covariates(cities, stem):
    """Median exposure against each morphology covariate, one panel per
    covariate. This is the mechanism figure: the CDF overlay shows the spread,
    these panels show what drives it."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    try:
        import scienceplots  # noqa: F401

        plt.style.use(["science", "ieee"])
    except Exception:
        pass

    panels = [
        ("los_fraction", "geometric LOS fraction"),
        ("roof_height_mean_m", "mean roof height [m]"),
        ("building_density_km2", r"buildings per km$^2$"),
        ("serving_distance_mean_m", "mean serving distance [m]"),
    ]
    rows = [(c, c.get("covariates") or {}) for c in cities if c.get("median") is not None]
    if not rows or not any(cov for _, cov in rows):
        print("no covariates in summaries; skipping covariate figure")
        return False

    fig, axes = plt.subplots(2, 2, figsize=(5.2, 4.0))
    for ax, (key, label) in zip(axes.ravel(), panels, strict=False):
        xs, ys, names = [], [], []
        for c, cov in rows:
            if cov.get(key) is None:
                continue
            xs.append(cov[key])
            ys.append(c["median"])
            names.append(str(c.get("name", "?")).replace("_", " ").title())
        if xs:
            ax.scatter(xs, ys, s=14, c="#3d5a80", zorder=3)
            for x, y, nm in zip(xs, ys, names, strict=False):
                ax.annotate(nm, (x, y), fontsize=4, xytext=(2, 2), textcoords="offset points")
            ax.set_yscale("log")
        ax.set_xlabel(label)
        ax.set_ylabel("median exposure [W]")
    fig.tight_layout()
    fig.savefig(f"{stem}.pdf")
    fig.savefig(f"{stem}.png", dpi=220)
    plt.close(fig)
    print(f"rendered {stem}.pdf and .png from {len(rows)} cities")
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results/cities")
    args = ap.parse_args(argv)
    res = Path(args.results)
    FIGS.mkdir(parents=True, exist_ok=True)

    summary = json.loads((res / "cities_summary.json").read_text())
    cities = summary.get("cities", [])

    if cities:
        _render_overlay(cities, str(FIGS / "cities_cdf"))
        _render_covariates(cities, str(FIGS / "cities_covariates"))
    else:
        print("WARNING: no cities in summary; build will miss the figure")

    headline = cities[0].get("headline", "exposure") if cities else "exposure"
    have_cov = any(c.get("covariates") for c in cities)
    lines = [
        "% Auto-generated by make_report.py. Do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Per-city population exposure ({headline.replace('_', '-')}): median and 95th percentile"
        + (", with morphology covariates (geometric LOS fraction, mean roof height)." if have_cov else ".")
        + "}}",
        "\\label{tab:cities}",
        "\\begin{tabular}{l" + ("cccc" if have_cov else "cc") + "}",
        "\\toprule",
        ("City & Median & p95 & LOS & $\\bar h$ [m] \\\\" if have_cov else "City & Median & p95 \\\\"),
        "\\midrule",
    ]
    for c in cities:
        name = str(c.get("name", "?")).replace("_", " ").title()
        row = f"{name} & {_fmt(c.get('median'))} & {_fmt(c.get('p95'))}"
        if have_cov:
            cov = c.get("covariates") or {}
            los = cov.get("los_fraction")
            hgt = cov.get("roof_height_mean_m")
            row += f" & {'--' if los is None else f'{los:.2f}'} & {'--' if hgt is None else f'{hgt:.0f}'}"
        lines.append(row + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (FIGS / "cities_table.tex").write_text("\n".join(lines))
    print(f"wrote {FIGS / 'cities_table.tex'} with {len(cities)} cities")
    print(f"succeeded: {summary.get('n_cities_succeeded')}/{summary.get('n_cities_requested')} cities")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
