"""Assemble the report's generated artifacts from a study batch.

Reads ``results/cities/cities_summary.json`` (written by
``aegis.study.run_cities``), copies the overlay CDF figure into ``figures/``,
and writes ``figures/cities_table.tex`` (per-city median and p95). Run after the
batch, then build with pdflatex. See README.md.

Usage:
    python papers/city-exposure-study/make_report.py [--results results/cities]
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

HERE = Path(__file__).parent
FIGS = HERE / "figures"


def _fmt(x):
    return "--" if x is None else f"\\num{{{x:.3e}}}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results/cities")
    args = ap.parse_args(argv)
    res = Path(args.results)
    FIGS.mkdir(parents=True, exist_ok=True)

    summary = json.loads((res / "cities_summary.json").read_text())
    cities = summary.get("cities", [])

    pdf = res / "cities_cdf.pdf"
    if pdf.exists():
        shutil.copy(pdf, FIGS / "cities_cdf.pdf")
        print(f"copied {pdf} -> {FIGS / 'cities_cdf.pdf'}")
    else:
        print(f"WARNING: {pdf} not found; build will miss the figure")

    headline = cities[0].get("headline", "exposure") if cities else "exposure"
    lines = [
        "% Auto-generated by make_report.py. Do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Per-city population exposure ({headline.replace('_', '-')}): "
        "median and 95th percentile.}}",
        "\\label{tab:cities}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "City & Median & p95 \\\\",
        "\\midrule",
    ]
    for c in cities:
        name = str(c.get("name", "?")).replace("_", " ").title()
        lines.append(f"{name} & {_fmt(c.get('median'))} & {_fmt(c.get('p95'))} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (FIGS / "cities_table.tex").write_text("\n".join(lines))
    print(f"wrote {FIGS / 'cities_table.tex'} with {len(cities)} cities")
    print(f"succeeded: {summary.get('n_cities_succeeded')}/{summary.get('n_cities_requested')} cities")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
