name: Label issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubicloud-standard-2
    steps:
      - uses: github/issue-labeler@v3
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
